export const SIMPLE_ACTION='SIMPLE_ACTION'
export const CREATE_USER='CREATE_USER'
export const USER_LIST='USER_LIST'
export const USER_LIST_FAIL='USER_LIST_FAIL'
export const USER_ROLE='USER_ROLE'
export const USER_COUNT='USER_COUNT'
export const IS_DOMAIN_USER='IS_DOMAIN_USER'
export const ADDUSER_LIST= 'ADDUSER_LIST'
export const ADDEXIST_USER= 'ADDEXIST_USER'
export const ADDEXIST_USERAD= 'ADDEXIST_USERAD'
export const USER_FILTER_COUNT='USER_FILTER_COUNT'
export const DELETE_USER='DELETE_USER'
export const ORGANISATION_LIST='ORGANISATION_LIST'
export const CREATE_ORGANISATION='CREATE_ORGANISATION'




